[package]
name = "ray"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
png = "0.17.13"
rand = "0.8.5"
rayon = "1.10.0"

[lib]
name = "engine"
path = "src/lib.rs"

[[bin]]
name = "ray"
path = "src/main.rs"
